// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PZPZF2aHfbrWAx35zGSEI3s0fezqIzc',
    appId: '1:435217031522:web:59c7eb4a414d4e22360c3b',
    messagingSenderId: '435217031522',
    projectId: 'mini-diariusz',
    authDomain: 'mini-diariusz.firebaseapp.com',
    storageBucket: 'mini-diariusz.appspot.com',
    measurementId: 'G-82JHZQCXK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-j8RR5AQBfHJ-2Ev720IevaqJYnCqe0',
    appId: '1:435217031522:android:b0ae0cf058edd578360c3b',
    messagingSenderId: '435217031522',
    projectId: 'mini-diariusz',
    storageBucket: 'mini-diariusz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2YQqNDuSvZoqgSlw5wmaaZwJNRuPEgE',
    appId: '1:435217031522:ios:a62be2bff6621392360c3b',
    messagingSenderId: '435217031522',
    projectId: 'mini-diariusz',
    storageBucket: 'mini-diariusz.appspot.com',
    iosBundleId: 'com.maciejmalinowski.miniDiariusz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2YQqNDuSvZoqgSlw5wmaaZwJNRuPEgE',
    appId: '1:435217031522:ios:bb996f406fd26f50360c3b',
    messagingSenderId: '435217031522',
    projectId: 'mini-diariusz',
    storageBucket: 'mini-diariusz.appspot.com',
    iosBundleId: 'com.maciejmalinowski.miniDiariusz.RunnerTests',
  );
}
